-- =========================
-- USUÁRIOS
-- =========================
CREATE TABLE IF NOT EXISTS USUARIOS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    U_LOGIN TEXT UNIQUE NOT NULL,
    U_SENHA_HASH TEXT NOT NULL,
    U_PERFIL TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS IDX_USUARIOS_LOGIN ON USUARIOS(U_LOGIN);

-- =========================
-- LOGS (AUDITORIA)
-- =========================
CREATE TABLE IF NOT EXISTS LOGS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    L_USUARIO TEXT,
    L_ACAO TEXT,
    L_DATA TEXT
);

CREATE INDEX IF NOT EXISTS IDX_LOGS_USUARIO_DATA ON LOGS(L_USUARIO, L_DATA);

-- =========================
-- PRODUTOS (SB1) + CM + RESERVA
-- =========================
CREATE TABLE IF NOT EXISTS SB1_PRODUTOS (
    B1_COD TEXT NOT NULL,
    B1_DESC TEXT,
    B1_PRECO REAL NOT NULL DEFAULT 0,
    B1_ESTOQUE INTEGER NOT NULL DEFAULT 0,
    B1_RESERVADO INTEGER NOT NULL DEFAULT 0,
    B1_CM REAL NOT NULL DEFAULT 0,
    B1_FILIAL TEXT NOT NULL,
    PRIMARY KEY (B1_COD, B1_FILIAL)
);

CREATE INDEX IF NOT EXISTS IDX_SB1_FILIAL ON SB1_PRODUTOS(B1_FILIAL);

-- =========================
-- PEDIDOS (SC5/SC6)
-- =========================
CREATE TABLE IF NOT EXISTS SC5_PEDIDOS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    C5_DATA TEXT NOT NULL,
    C5_FILIAL TEXT NOT NULL,
    C5_VALOR_TOTAL REAL NOT NULL DEFAULT 0,
    C5_USUARIO TEXT NOT NULL,
    C5_STATUS TEXT NOT NULL DEFAULT 'ABERTO' -- ABERTO | FATURADO | CANCELADO
);

CREATE INDEX IF NOT EXISTS IDX_SC5_FILIAL_DATA ON SC5_PEDIDOS(C5_FILIAL, C5_DATA);

CREATE TABLE IF NOT EXISTS SC6_ITENS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    C6_PEDIDO_ID INTEGER NOT NULL,
    C6_PRODUTO TEXT NOT NULL,
    C6_QTD INTEGER NOT NULL,
    C6_VALOR REAL NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS IDX_SC6_PEDIDO ON SC6_ITENS(C6_PEDIDO_ID);
CREATE INDEX IF NOT EXISTS IDX_SC6_PRODUTO ON SC6_ITENS(C6_PRODUTO);

-- =========================
-- MOVIMENTAÇÃO DE ESTOQUE (SD3)
-- =========================
CREATE TABLE IF NOT EXISTS SD3_MOV (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    D3_DATA TEXT NOT NULL,
    D3_FILIAL TEXT NOT NULL,
    D3_PRODUTO TEXT NOT NULL,
    D3_TIPO TEXT NOT NULL,          -- 'E' entrada, 'S' saída
    D3_QTD INTEGER NOT NULL,
    D3_CUSTO_UNIT REAL NOT NULL DEFAULT 0,
    D3_VALOR REAL NOT NULL DEFAULT 0,
    D3_ORIGEM TEXT,
    D3_REF TEXT,
    D3_USUARIO TEXT
);

CREATE INDEX IF NOT EXISTS IDX_SD3_PROD_FILIAL ON SD3_MOV(D3_PRODUTO, D3_FILIAL);
CREATE INDEX IF NOT EXISTS IDX_SD3_FILIAL_DATA ON SD3_MOV(D3_FILIAL, D3_DATA);
CREATE INDEX IF NOT EXISTS IDX_SD3_ORIGEM_REF ON SD3_MOV(D3_ORIGEM, D3_REF);

-- =========================
-- RESERVAS (pré-venda)
-- =========================
CREATE TABLE IF NOT EXISTS SZ0_RESERVA (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Z0_DATA TEXT NOT NULL,
    Z0_FILIAL TEXT NOT NULL,
    Z0_PRODUTO TEXT NOT NULL,
    Z0_QTD INTEGER NOT NULL,
    Z0_USUARIO TEXT NOT NULL,
    Z0_STATUS TEXT NOT NULL DEFAULT 'ABERTA' -- ABERTA | CONFIRMADA | CANCELADA
);

CREATE INDEX IF NOT EXISTS IDX_SZ0_FILIAL_STATUS ON SZ0_RESERVA(Z0_FILIAL, Z0_STATUS);

-- =========================
-- TRANSFERÊNCIA (rastreamento opcional)
-- =========================
CREATE TABLE IF NOT EXISTS ST0_TRANSFER (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    T0_DATA TEXT NOT NULL,
    T0_PRODUTO TEXT NOT NULL,
    T0_QTD INTEGER NOT NULL,
    T0_ORIGEM TEXT NOT NULL,
    T0_DESTINO TEXT NOT NULL,
    T0_USUARIO TEXT NOT NULL,
    T0_REF TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS IDX_ST0_REF ON ST0_TRANSFER(T0_REF);

-- =========================
-- FINANCEIRO (AR/AP)
-- =========================
CREATE TABLE IF NOT EXISTS SE1_AR (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    E1_DATA TEXT NOT NULL,
    E1_VENC TEXT NOT NULL,
    E1_CLIENTE TEXT,
    E1_VALOR REAL NOT NULL,
    E1_STATUS TEXT NOT NULL DEFAULT 'ABERTO', -- ABERTO | BAIXADO | CANCELADO
    E1_REF TEXT, -- pedido_id
    E1_FILIAL TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS IDX_SE1_STATUS_FILIAL ON SE1_AR(E1_STATUS, E1_FILIAL);

CREATE TABLE IF NOT EXISTS SF1_AP (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    F1_DATA TEXT NOT NULL,
    F1_VENC TEXT NOT NULL,
    F1_FORN TEXT,
    F1_VALOR REAL NOT NULL,
    F1_STATUS TEXT NOT NULL DEFAULT 'ABERTO', -- ABERTO | BAIXADO | CANCELADO
    F1_REF TEXT,
    F1_FILIAL TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS IDX_SF1_STATUS_FILIAL ON SF1_AP(F1_STATUS, F1_FILIAL);