-- Bloco 7.1 - Fechamento mensal por filial

IF OBJECT_ID('dbo.SF7_FECHAMENTO', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.SF7_FECHAMENTO (
        ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        F7_FILIAL NVARCHAR(10) NOT NULL,
        F7_ANO INT NOT NULL,
        F7_MES INT NOT NULL,
        F7_FECHADO BIT NOT NULL DEFAULT (1),
        F7_USUARIO NVARCHAR(100) NULL,
        F7_DATA DATETIME2(0) NOT NULL DEFAULT (SYSDATETIME()),
        D_E_L_E_T_ CHAR(1) NULL,
        R_E_C_N_O_ INT NULL,
        R_E_C_D_E_L_ INT NULL
    );
END

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = 'UX_SF7_FILIAL_ANO_MES'
      AND object_id = OBJECT_ID('dbo.SF7_FECHAMENTO')
)
BEGIN
    CREATE UNIQUE INDEX UX_SF7_FILIAL_ANO_MES
    ON dbo.SF7_FECHAMENTO (F7_FILIAL, F7_ANO, F7_MES)
    WHERE D_E_L_E_T_ IS NULL;
END