-- Bloco 7.3 - Multi-filial (SM0_EMPRESA)

IF COL_LENGTH('dbo.SM0_EMPRESA', 'D_E_L_E_T_') IS NULL
    ALTER TABLE dbo.SM0_EMPRESA ADD D_E_L_E_T_ CHAR(1) NULL;
IF COL_LENGTH('dbo.SM0_EMPRESA', 'R_E_C_N_O_') IS NULL
    ALTER TABLE dbo.SM0_EMPRESA ADD R_E_C_N_O_ INT NULL;
IF COL_LENGTH('dbo.SM0_EMPRESA', 'R_E_C_D_E_L_') IS NULL
    ALTER TABLE dbo.SM0_EMPRESA ADD R_E_C_D_E_L_ INT NULL;

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = 'UX_SM0_FILIAL'
      AND object_id = OBJECT_ID('dbo.SM0_EMPRESA')
)
BEGIN
    CREATE UNIQUE INDEX UX_SM0_FILIAL
    ON dbo.SM0_EMPRESA (M0_FILIAL)
    WHERE D_E_L_E_T_ IS NULL;
END
