-- Bloco 7.2 - Integração fiscal extra (NCM + CFOP por produto)

IF COL_LENGTH('dbo.SB1_PRODUTOS', 'B1_NCM') IS NULL
    ALTER TABLE dbo.SB1_PRODUTOS ADD B1_NCM NVARCHAR(20) NULL;

IF OBJECT_ID('dbo.SF8_FISCAL_NCM', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.SF8_FISCAL_NCM (
        ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        F8_FILIAL NVARCHAR(10) NOT NULL,
        F8_NCM NVARCHAR(20) NOT NULL,
        F8_CFOP NVARCHAR(10) NOT NULL,
        F8_ICMS DECIMAL(9,4) NULL,
        F8_IPI DECIMAL(9,4) NULL,
        F8_ATIVO BIT NOT NULL DEFAULT (1),
        D_E_L_E_T_ CHAR(1) NULL,
        R_E_C_N_O_ INT NULL,
        R_E_C_D_E_L_ INT NULL
    );
END

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = 'UX_SF8_FILIAL_NCM'
      AND object_id = OBJECT_ID('dbo.SF8_FISCAL_NCM')
)
BEGIN
    CREATE UNIQUE INDEX UX_SF8_FILIAL_NCM
    ON dbo.SF8_FISCAL_NCM (F8_FILIAL, F8_NCM)
    WHERE D_E_L_E_T_ IS NULL;
END
