-- Bloco 9.1 - Tributos avançados (PIS/COFINS/ICMS ST/DIFAL + CST)
USE ERP_PROTHEUS;
GO

-- SF4_FISCAL (TES)
IF COL_LENGTH('dbo.SF4_FISCAL', 'F4_PIS') IS NULL
    ALTER TABLE dbo.SF4_FISCAL ADD F4_PIS DECIMAL(9,4) NULL;
IF COL_LENGTH('dbo.SF4_FISCAL', 'F4_COFINS') IS NULL
    ALTER TABLE dbo.SF4_FISCAL ADD F4_COFINS DECIMAL(9,4) NULL;
IF COL_LENGTH('dbo.SF4_FISCAL', 'F4_ICMS_ST') IS NULL
    ALTER TABLE dbo.SF4_FISCAL ADD F4_ICMS_ST DECIMAL(9,4) NULL;
IF COL_LENGTH('dbo.SF4_FISCAL', 'F4_DIFAL') IS NULL
    ALTER TABLE dbo.SF4_FISCAL ADD F4_DIFAL DECIMAL(9,4) NULL;
IF COL_LENGTH('dbo.SF4_FISCAL', 'F4_CST_ICMS') IS NULL
    ALTER TABLE dbo.SF4_FISCAL ADD F4_CST_ICMS NVARCHAR(3) NULL;
IF COL_LENGTH('dbo.SF4_FISCAL', 'F4_CSOSN') IS NULL
    ALTER TABLE dbo.SF4_FISCAL ADD F4_CSOSN NVARCHAR(3) NULL;
IF COL_LENGTH('dbo.SF4_FISCAL', 'F4_CST_PIS') IS NULL
    ALTER TABLE dbo.SF4_FISCAL ADD F4_CST_PIS NVARCHAR(3) NULL;
IF COL_LENGTH('dbo.SF4_FISCAL', 'F4_CST_COFINS') IS NULL
    ALTER TABLE dbo.SF4_FISCAL ADD F4_CST_COFINS NVARCHAR(3) NULL;

-- SF5_FISCAL_REGRAS (override por cliente/produto)
IF COL_LENGTH('dbo.SF5_FISCAL_REGRAS', 'F5_PIS') IS NULL
    ALTER TABLE dbo.SF5_FISCAL_REGRAS ADD F5_PIS DECIMAL(9,4) NULL;
IF COL_LENGTH('dbo.SF5_FISCAL_REGRAS', 'F5_COFINS') IS NULL
    ALTER TABLE dbo.SF5_FISCAL_REGRAS ADD F5_COFINS DECIMAL(9,4) NULL;
IF COL_LENGTH('dbo.SF5_FISCAL_REGRAS', 'F5_ICMS_ST') IS NULL
    ALTER TABLE dbo.SF5_FISCAL_REGRAS ADD F5_ICMS_ST DECIMAL(9,4) NULL;
IF COL_LENGTH('dbo.SF5_FISCAL_REGRAS', 'F5_DIFAL') IS NULL
    ALTER TABLE dbo.SF5_FISCAL_REGRAS ADD F5_DIFAL DECIMAL(9,4) NULL;
IF COL_LENGTH('dbo.SF5_FISCAL_REGRAS', 'F5_CST_ICMS') IS NULL
    ALTER TABLE dbo.SF5_FISCAL_REGRAS ADD F5_CST_ICMS NVARCHAR(3) NULL;
IF COL_LENGTH('dbo.SF5_FISCAL_REGRAS', 'F5_CSOSN') IS NULL
    ALTER TABLE dbo.SF5_FISCAL_REGRAS ADD F5_CSOSN NVARCHAR(3) NULL;
IF COL_LENGTH('dbo.SF5_FISCAL_REGRAS', 'F5_CST_PIS') IS NULL
    ALTER TABLE dbo.SF5_FISCAL_REGRAS ADD F5_CST_PIS NVARCHAR(3) NULL;
IF COL_LENGTH('dbo.SF5_FISCAL_REGRAS', 'F5_CST_COFINS') IS NULL
    ALTER TABLE dbo.SF5_FISCAL_REGRAS ADD F5_CST_COFINS NVARCHAR(3) NULL;

-- SF2_NOTAS (totais)
IF COL_LENGTH('dbo.SF2_NOTAS', 'F2_PIS') IS NULL
    ALTER TABLE dbo.SF2_NOTAS ADD F2_PIS DECIMAL(18,2) NULL;
IF COL_LENGTH('dbo.SF2_NOTAS', 'F2_COFINS') IS NULL
    ALTER TABLE dbo.SF2_NOTAS ADD F2_COFINS DECIMAL(18,2) NULL;
IF COL_LENGTH('dbo.SF2_NOTAS', 'F2_ICMS_ST') IS NULL
    ALTER TABLE dbo.SF2_NOTAS ADD F2_ICMS_ST DECIMAL(18,2) NULL;
IF COL_LENGTH('dbo.SF2_NOTAS', 'F2_DIFAL') IS NULL
    ALTER TABLE dbo.SF2_NOTAS ADD F2_DIFAL DECIMAL(18,2) NULL;

-- SD2_ITENS (por item)
IF COL_LENGTH('dbo.SD2_ITENS', 'D2_PIS') IS NULL
    ALTER TABLE dbo.SD2_ITENS ADD D2_PIS DECIMAL(18,2) NULL;
IF COL_LENGTH('dbo.SD2_ITENS', 'D2_COFINS') IS NULL
    ALTER TABLE dbo.SD2_ITENS ADD D2_COFINS DECIMAL(18,2) NULL;
IF COL_LENGTH('dbo.SD2_ITENS', 'D2_ICMS_ST') IS NULL
    ALTER TABLE dbo.SD2_ITENS ADD D2_ICMS_ST DECIMAL(18,2) NULL;
IF COL_LENGTH('dbo.SD2_ITENS', 'D2_DIFAL') IS NULL
    ALTER TABLE dbo.SD2_ITENS ADD D2_DIFAL DECIMAL(18,2) NULL;
IF COL_LENGTH('dbo.SD2_ITENS', 'D2_CST_ICMS') IS NULL
    ALTER TABLE dbo.SD2_ITENS ADD D2_CST_ICMS NVARCHAR(3) NULL;
IF COL_LENGTH('dbo.SD2_ITENS', 'D2_CSOSN') IS NULL
    ALTER TABLE dbo.SD2_ITENS ADD D2_CSOSN NVARCHAR(3) NULL;
IF COL_LENGTH('dbo.SD2_ITENS', 'D2_CST_PIS') IS NULL
    ALTER TABLE dbo.SD2_ITENS ADD D2_CST_PIS NVARCHAR(3) NULL;
IF COL_LENGTH('dbo.SD2_ITENS', 'D2_CST_COFINS') IS NULL
    ALTER TABLE dbo.SD2_ITENS ADD D2_CST_COFINS NVARCHAR(3) NULL;
