-- Bloco 4.3 - Auditoria (logs) via trigger
-- Requer tabela dbo.LOGS existente

-- SC5_PEDIDOS
IF OBJECT_ID('dbo.TR_LOG_SC5', 'TR') IS NULL
BEGIN
EXEC('
CREATE TRIGGER dbo.TR_LOG_SC5
ON dbo.SC5_PEDIDOS
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @acao NVARCHAR(20) =
        CASE WHEN EXISTS(SELECT 1 FROM inserted) AND EXISTS(SELECT 1 FROM deleted) THEN ''UPDATE''
             WHEN EXISTS(SELECT 1 FROM inserted) THEN ''INSERT''
             ELSE ''DELETE'' END;

    INSERT INTO dbo.LOGS (L_USUARIO, L_ACAO, L_DATA)
    SELECT
      COALESCE(i.C5_USUARIO, d.C5_USUARIO, SYSTEM_USER),
      ''SC5_PEDIDOS '' + @acao + '' ID='' + CAST(COALESCE(i.ID, d.ID) AS NVARCHAR(20)),
      SYSDATETIME()
    FROM inserted i
    FULL JOIN deleted d ON i.ID = d.ID;
END
');
END

-- SC6_ITENS
IF OBJECT_ID('dbo.TR_LOG_SC6', 'TR') IS NULL
BEGIN
EXEC('
CREATE TRIGGER dbo.TR_LOG_SC6
ON dbo.SC6_ITENS
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @acao NVARCHAR(20) =
        CASE WHEN EXISTS(SELECT 1 FROM inserted) AND EXISTS(SELECT 1 FROM deleted) THEN ''UPDATE''
             WHEN EXISTS(SELECT 1 FROM inserted) THEN ''INSERT''
             ELSE ''DELETE'' END;

    INSERT INTO dbo.LOGS (L_USUARIO, L_ACAO, L_DATA)
    SELECT
      COALESCE(i.C6_USUARIO_ALT, i.C6_USUARIO_DEL, d.C6_USUARIO_ALT, d.C6_USUARIO_DEL, SYSTEM_USER),
      ''SC6_ITENS '' + @acao + '' ID='' + CAST(COALESCE(i.ID, d.ID) AS NVARCHAR(20)),
      SYSDATETIME()
    FROM inserted i
    FULL JOIN deleted d ON i.ID = d.ID;
END
');
END

-- SF2_NOTAS
IF OBJECT_ID('dbo.TR_LOG_SF2', 'TR') IS NULL
BEGIN
EXEC('
CREATE TRIGGER dbo.TR_LOG_SF2
ON dbo.SF2_NOTAS
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @acao NVARCHAR(20) =
        CASE WHEN EXISTS(SELECT 1 FROM inserted) AND EXISTS(SELECT 1 FROM deleted) THEN ''UPDATE''
             WHEN EXISTS(SELECT 1 FROM inserted) THEN ''INSERT''
             ELSE ''DELETE'' END;

    INSERT INTO dbo.LOGS (L_USUARIO, L_ACAO, L_DATA)
    SELECT
      COALESCE(i.F2_USUARIO_CANCEL, d.F2_USUARIO_CANCEL, SYSTEM_USER),
      ''SF2_NOTAS '' + @acao + '' ID='' + CAST(COALESCE(i.ID, d.ID) AS NVARCHAR(20)),
      SYSDATETIME()
    FROM inserted i
    FULL JOIN deleted d ON i.ID = d.ID;
END
');
END

-- SD2_ITENS
IF OBJECT_ID('dbo.TR_LOG_SD2', 'TR') IS NULL
BEGIN
EXEC('
CREATE TRIGGER dbo.TR_LOG_SD2
ON dbo.SD2_ITENS
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @acao NVARCHAR(20) =
        CASE WHEN EXISTS(SELECT 1 FROM inserted) AND EXISTS(SELECT 1 FROM deleted) THEN ''UPDATE''
             WHEN EXISTS(SELECT 1 FROM inserted) THEN ''INSERT''
             ELSE ''DELETE'' END;

    INSERT INTO dbo.LOGS (L_USUARIO, L_ACAO, L_DATA)
    SELECT
      COALESCE(i.D2_USUARIO_CANCEL, d.D2_USUARIO_CANCEL, SYSTEM_USER),
      ''SD2_ITENS '' + @acao + '' ID='' + CAST(COALESCE(i.ID, d.ID) AS NVARCHAR(20)),
      SYSDATETIME()
    FROM inserted i
    FULL JOIN deleted d ON i.ID = d.ID;
END
');
END

-- SE1_AR
IF OBJECT_ID('dbo.TR_LOG_SE1', 'TR') IS NULL
BEGIN
EXEC('
CREATE TRIGGER dbo.TR_LOG_SE1
ON dbo.SE1_AR
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @acao NVARCHAR(20) =
        CASE WHEN EXISTS(SELECT 1 FROM inserted) AND EXISTS(SELECT 1 FROM deleted) THEN ''UPDATE''
             WHEN EXISTS(SELECT 1 FROM inserted) THEN ''INSERT''
             ELSE ''DELETE'' END;

    INSERT INTO dbo.LOGS (L_USUARIO, L_ACAO, L_DATA)
    SELECT
      SYSTEM_USER,
      ''SE1_AR '' + @acao + '' ID='' + CAST(COALESCE(i.ID, d.ID) AS NVARCHAR(20)),
      SYSDATETIME()
    FROM inserted i
    FULL JOIN deleted d ON i.ID = d.ID;
END
');
END

-- SF1_AP
IF OBJECT_ID('dbo.TR_LOG_SF1', 'TR') IS NULL
BEGIN
EXEC('
CREATE TRIGGER dbo.TR_LOG_SF1
ON dbo.SF1_AP
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @acao NVARCHAR(20) =
        CASE WHEN EXISTS(SELECT 1 FROM inserted) AND EXISTS(SELECT 1 FROM deleted) THEN ''UPDATE''
             WHEN EXISTS(SELECT 1 FROM inserted) THEN ''INSERT''
             ELSE ''DELETE'' END;

    INSERT INTO dbo.LOGS (L_USUARIO, L_ACAO, L_DATA)
    SELECT
      SYSTEM_USER,
      ''SF1_AP '' + @acao + '' ID='' + CAST(COALESCE(i.ID, d.ID) AS NVARCHAR(20)),
      SYSDATETIME()
    FROM inserted i
    FULL JOIN deleted d ON i.ID = d.ID;
END
');
END
