-- Regras fiscais avançadas (SF5_FISCAL_REGRAS)
-- Prioridade: mais específico (cliente+produto) > cliente ou produto > genérico

IF OBJECT_ID('dbo.SF5_FISCAL_REGRAS', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.SF5_FISCAL_REGRAS (
        ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        F5_FILIAL NVARCHAR(10) NOT NULL,
        F5_TES NVARCHAR(10) NOT NULL,
        F5_CLIENTE_COD NVARCHAR(20) NULL,
        F5_PRODUTO NVARCHAR(50) NULL,
        F5_CFOP NVARCHAR(10) NULL,
        F5_ICMS DECIMAL(9,4) NULL,
        F5_IPI DECIMAL(9,4) NULL,
        F5_GERA_TIT BIT NULL,
        F5_GERA_EST BIT NULL,
        F5_PRIORIDADE INT NOT NULL DEFAULT (0),
        F5_ATIVO BIT NOT NULL DEFAULT (1),
        D_E_L_E_T_ CHAR(1) NULL,
        R_E_C_N_O_ INT NULL,
        R_E_C_D_E_L_ INT NULL
    );
END

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = 'IX_SF5_FISCAL_REGRAS_FILTRO'
      AND object_id = OBJECT_ID('dbo.SF5_FISCAL_REGRAS')
)
BEGIN
    CREATE INDEX IX_SF5_FISCAL_REGRAS_FILTRO
    ON dbo.SF5_FISCAL_REGRAS (F5_FILIAL, F5_TES, F5_ATIVO, F5_CLIENTE_COD, F5_PRODUTO, F5_PRIORIDADE);
END
